/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as CompraSucessoRouteImport } from './routes/compra/sucesso'
import { Route as ContasIndexRouteImport } from './routes/contas/index'
import { Route as ContasIdRouteImport } from './routes/contas/$id'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard/perfil'
import { Route as AdminContasIndexRouteImport } from './routes/admin/contas/index'
import { Route as AdminContasNovaRouteImport } from './routes/admin/contas/nova'
import { Route as DashboardComprasIndexRouteImport } from './routes/dashboard/compras/index'
import { Route as DashboardComprasIdRouteImport } from './routes/dashboard/compras/$id'
import { Route as AdminContasIdEditarRouteImport } from './routes/admin/contas/$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompraSucessoRoute = CompraSucessoRouteImport.update({
  id: '/compra/sucesso',
  path: '/compra/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasIndexRoute = ContasIndexRouteImport.update({
  id: '/contas/',
  path: '/contas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasIdRoute = ContasIdRouteImport.update({
  id: '/contas/$id',
  path: '/contas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/dashboard/perfil',
  path: '/dashboard/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContasIndexRoute = AdminContasIndexRouteImport.update({
  id: '/admin/contas/',
  path: '/admin/contas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContasNovaRoute = AdminContasNovaRouteImport.update({
  id: '/admin/contas/nova',
  path: '/admin/contas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComprasIndexRoute = DashboardComprasIndexRouteImport.update({
  id: '/dashboard/compras/',
  path: '/dashboard/compras/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComprasIdRoute = DashboardComprasIdRouteImport.update({
  id: '/dashboard/compras/$id',
  path: '/dashboard/compras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContasIdEditarRoute = AdminContasIdEditarRouteImport.update({
  id: '/admin/contas/$id/editar',
  path: '/admin/contas/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/suporte': typeof SuporteRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/compra/sucesso': typeof CompraSucessoRoute
  '/contas/$id': typeof ContasIdRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/contas/': typeof ContasIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/contas/nova': typeof AdminContasNovaRoute
  '/dashboard/compras/$id': typeof DashboardComprasIdRoute
  '/admin/contas/': typeof AdminContasIndexRoute
  '/dashboard/compras/': typeof DashboardComprasIndexRoute
  '/admin/contas/$id/editar': typeof AdminContasIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/suporte': typeof SuporteRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/compra/sucesso': typeof CompraSucessoRoute
  '/contas/$id': typeof ContasIdRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/contas': typeof ContasIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/contas/nova': typeof AdminContasNovaRoute
  '/dashboard/compras/$id': typeof DashboardComprasIdRoute
  '/admin/contas': typeof AdminContasIndexRoute
  '/dashboard/compras': typeof DashboardComprasIndexRoute
  '/admin/contas/$id/editar': typeof AdminContasIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/suporte': typeof SuporteRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/compra/sucesso': typeof CompraSucessoRoute
  '/contas/$id': typeof ContasIdRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/contas/': typeof ContasIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/contas/nova': typeof AdminContasNovaRoute
  '/dashboard/compras/$id': typeof DashboardComprasIdRoute
  '/admin/contas/': typeof AdminContasIndexRoute
  '/dashboard/compras/': typeof DashboardComprasIndexRoute
  '/admin/contas/$id/editar': typeof AdminContasIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/login'
    | '/register'
    | '/suporte'
    | '/admin/clientes'
    | '/admin/pedidos'
    | '/checkout/$id'
    | '/compra/sucesso'
    | '/contas/$id'
    | '/dashboard/perfil'
    | '/admin/'
    | '/contas/'
    | '/dashboard/'
    | '/admin/contas/nova'
    | '/dashboard/compras/$id'
    | '/admin/contas/'
    | '/dashboard/compras/'
    | '/admin/contas/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/login'
    | '/register'
    | '/suporte'
    | '/admin/clientes'
    | '/admin/pedidos'
    | '/checkout/$id'
    | '/compra/sucesso'
    | '/contas/$id'
    | '/dashboard/perfil'
    | '/admin'
    | '/contas'
    | '/dashboard'
    | '/admin/contas/nova'
    | '/dashboard/compras/$id'
    | '/admin/contas'
    | '/dashboard/compras'
    | '/admin/contas/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/login'
    | '/register'
    | '/suporte'
    | '/admin/clientes'
    | '/admin/pedidos'
    | '/checkout/$id'
    | '/compra/sucesso'
    | '/contas/$id'
    | '/dashboard/perfil'
    | '/admin/'
    | '/contas/'
    | '/dashboard/'
    | '/admin/contas/nova'
    | '/dashboard/compras/$id'
    | '/admin/contas/'
    | '/dashboard/compras/'
    | '/admin/contas/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SuporteRoute: typeof SuporteRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  CompraSucessoRoute: typeof CompraSucessoRoute
  ContasIdRoute: typeof ContasIdRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContasIndexRoute: typeof ContasIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminContasNovaRoute: typeof AdminContasNovaRoute
  DashboardComprasIdRoute: typeof DashboardComprasIdRoute
  AdminContasIndexRoute: typeof AdminContasIndexRoute
  DashboardComprasIndexRoute: typeof DashboardComprasIndexRoute
  AdminContasIdEditarRoute: typeof AdminContasIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compra/sucesso': {
      id: '/compra/sucesso'
      path: '/compra/sucesso'
      fullPath: '/compra/sucesso'
      preLoaderRoute: typeof CompraSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas/': {
      id: '/contas/'
      path: '/contas'
      fullPath: '/contas/'
      preLoaderRoute: typeof ContasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas/$id': {
      id: '/contas/$id'
      path: '/contas/$id'
      fullPath: '/contas/$id'
      preLoaderRoute: typeof ContasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/dashboard/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contas/': {
      id: '/admin/contas/'
      path: '/admin/contas'
      fullPath: '/admin/contas/'
      preLoaderRoute: typeof AdminContasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contas/nova': {
      id: '/admin/contas/nova'
      path: '/admin/contas/nova'
      fullPath: '/admin/contas/nova'
      preLoaderRoute: typeof AdminContasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/compras/': {
      id: '/dashboard/compras/'
      path: '/dashboard/compras'
      fullPath: '/dashboard/compras/'
      preLoaderRoute: typeof DashboardComprasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/compras/$id': {
      id: '/dashboard/compras/$id'
      path: '/dashboard/compras/$id'
      fullPath: '/dashboard/compras/$id'
      preLoaderRoute: typeof DashboardComprasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contas/$id/editar': {
      id: '/admin/contas/$id/editar'
      path: '/admin/contas/$id/editar'
      fullPath: '/admin/contas/$id/editar'
      preLoaderRoute: typeof AdminContasIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SuporteRoute: SuporteRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  CompraSucessoRoute: CompraSucessoRoute,
  ContasIdRoute: ContasIdRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContasIndexRoute: ContasIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminContasNovaRoute: AdminContasNovaRoute,
  DashboardComprasIdRoute: DashboardComprasIdRoute,
  AdminContasIndexRoute: AdminContasIndexRoute,
  DashboardComprasIndexRoute: DashboardComprasIndexRoute,
  AdminContasIdEditarRoute: AdminContasIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
